# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-28 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backoffice', '0002_productreferences_sellpricermb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('checked_out', models.BooleanField(default=False, verbose_name='checked out ?')),
            ],
            options={
                'verbose_name_plural': 'carts',
                'ordering': ('-creation_date',),
                'verbose_name': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantité')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartsystem.Cart', verbose_name='cart')),
                ('product_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.ProductReferences')),
            ],
            options={
                'verbose_name_plural': 'items',
                'ordering': ('cart',),
                'verbose_name': 'item',
            },
        ),
    ]
