# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-28 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartsystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='locale',
            field=models.CharField(default='fr', max_length=10),
        ),
    ]
