# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 13:33
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import djmoney.models.fields
import filer.fields.image
import taggit.managers
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filer', '0007_auto_20161016_1055'),
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('ProductName', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('ProductName_fr', models.CharField(max_length=200, null=True, verbose_name='Nom du produit')),
                ('ProductName_en', models.CharField(max_length=200, null=True, verbose_name='Nom du produit')),
                ('ProductName_zh_hans', models.CharField(max_length=200, null=True, verbose_name='Nom du produit')),
                ('Description', tinymce.models.HTMLField(blank=True, null=True)),
                ('Description_fr', tinymce.models.HTMLField(blank=True, null=True)),
                ('Description_en', tinymce.models.HTMLField(blank=True, null=True)),
                ('Description_zh_hans', tinymce.models.HTMLField(blank=True, null=True)),
                ('RefCount', models.SmallIntegerField(default=0, verbose_name='Références')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='Marque')),
                ('OriginCountry', django_countries.fields.CountryField(max_length=2, verbose_name="Pays d'origine")),
                ('URL', models.URLField(blank=True, max_length=1000, null=True, verbose_name='Liens vers le site')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.IntegerField(default=0)),
                ('width', models.IntegerField(default=0)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Product')),
                ('image', filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='filer.Image')),
            ],
            options={
                'verbose_name': 'Images du produit',
                'verbose_name_plural': 'Images du produit',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=200)),
                ('URL', models.URLField(blank=True, max_length=3000, null=True, verbose_name='Lien vers la fiche produit')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Product')),
            ],
            options={
                'verbose_name': 'Liens vers les sites de vente',
                'verbose_name_plural': 'Liens vers les sites de vente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ref', models.CharField(max_length=200)),
                ('Ref_fr', models.CharField(max_length=200, null=True)),
                ('Ref_en', models.CharField(max_length=200, null=True)),
                ('Ref_zh_hans', models.CharField(max_length=200, null=True)),
                ('BuyPrice_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('HKD', 'Hong Kong Dollar'), ('GBP', 'Pound Sterling'), ('USD', 'US Dollar'), ('JPY', 'Yen'), ('CNY', 'Yuan Renminbi')], default='EUR', editable=False, max_length=3)),
                ('BuyPrice', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=10, null=True, verbose_name="Prix d'achat (€)")),
                ('SellPrice_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('HKD', 'Hong Kong Dollar'), ('GBP', 'Pound Sterling'), ('USD', 'US Dollar'), ('JPY', 'Yen'), ('CNY', 'Yuan Renminbi')], default='EUR', editable=False, max_length=3)),
                ('SellPrice', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=10, null=True, verbose_name='Prix de vente (€)')),
                ('MeasureUnit', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('cl', 'cl'), ('l', 'l')], default='g', max_length=3)),
                ('Measure', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Product')),
            ],
            options={
                'verbose_name': 'Reference',
                'verbose_name_plural': 'References',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubType', models.CharField(max_length=200, verbose_name='Sous-atégorie de produits')),
                ('SubType_fr', models.CharField(max_length=200, null=True, verbose_name='Sous-atégorie de produits')),
                ('SubType_en', models.CharField(max_length=200, null=True, verbose_name='Sous-atégorie de produits')),
                ('SubType_zh_hans', models.CharField(max_length=200, null=True, verbose_name='Sous-atégorie de produits')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=200, verbose_name='Catégorie de produits')),
                ('Type_fr', models.CharField(max_length=200, null=True, verbose_name='Catégorie de produits')),
                ('Type_en', models.CharField(max_length=200, null=True, verbose_name='Catégorie de produits')),
                ('Type_zh_hans', models.CharField(max_length=200, null=True, verbose_name='Catégorie de produits')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='Brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.ProductBrand', verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='product',
            name='MainPhoto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backoffice.ProductImage'),
        ),
        migrations.AddField(
            model_name='product',
            name='MainProductReference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backoffice.ProductReferences'),
        ),
        migrations.AddField(
            model_name='product',
            name='ProductSubType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.ProductSubType', verbose_name='Type de produit'),
        ),
        migrations.AddField(
            model_name='product',
            name='ProductType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.ProductType', verbose_name='Catégorie de produit'),
        ),
        migrations.AddField(
            model_name='product',
            name='Tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
