# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SubType', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sous-atégorie de produits')),
                ('Type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.ProductType')),
            ],
        ),
    ]
