# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 13:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_admin',
            new_name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Weight',
        ),
    ]
