# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 13:23
from __future__ import unicode_literals

from django.db import migrations
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20170524_1501'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.AddField(
            model_name='product',
            name='Weight',
            field=django_measurement.models.MeasurementField(blank=True, measurement_class='Mass', null=True, verbose_name='Poids (remplacé par Référence produit, à inactiver)'),
        ),
    ]
