# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_subproducttype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubProductType',
            new_name='ProductSubType',
        ),
    ]
