# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_auto_20170524_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='BuyPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='BuyPrice_currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='SellPrice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='SellPrice_currency',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Weight',
        ),
    ]
