# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0003_auto_20170514_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Marque')),
                ('OriginCountry', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductSubType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.ProductSubType'),
        ),
    ]
