# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0007_auto_20170514_1910'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='SellPrice',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='EUR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='SellPrice_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('HKD', 'Hong Kong Dollar'), ('GBP', 'Pound Sterling'), ('USD', 'US Dollar'), ('JPY', 'Yen'), ('CNY', 'Yuan Renminbi')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='BuyPrice',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='EUR', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='BuyPrice_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('HKD', 'Hong Kong Dollar'), ('GBP', 'Pound Sterling'), ('USD', 'US Dollar'), ('JPY', 'Yen'), ('CNY', 'Yuan Renminbi')], default='EUR', editable=False, max_length=3),
        ),
    ]
