# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 17:31
from __future__ import unicode_literals

import backoffice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0008_auto_20170514_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='Image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=backoffice.models.upload_location, width_field='width'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='width',
            field=models.IntegerField(default=0),
        ),
    ]
