# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 17:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0009_auto_20170514_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.Product'),
        ),
    ]
