# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 17:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0010_productimage_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.ProductType'),
        ),
    ]
