# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0011_product_producttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubtype',
            name='Type',
        ),
        migrations.AddField(
            model_name='product',
            name='Weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Poids en kg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.ProductBrand', verbose_name='Marque'),
        ),
        migrations.AlterField(
            model_name='product',
            name='BuyPrice',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='EUR', max_digits=10, null=True, verbose_name="Prix d'achat"),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductName',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom du produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductSubType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.ProductSubType', verbose_name='Type de produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.ProductType', verbose_name='Catégorie de produit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='SellPrice',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='EUR', max_digits=10, null=True, verbose_name='Prix de vente'),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='OriginCountry',
            field=django_countries.fields.CountryField(max_length=2, verbose_name="Pays d'origine"),
        ),
        migrations.AlterField(
            model_name='productbrand',
            name='URL',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Liens vers le site'),
        ),
    ]
