# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0013_productlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlink',
            name='Description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
