# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 20:08
from __future__ import unicode_literals

from django.db import migrations
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0014_productlink_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Weight',
            field=django_measurement.models.MeasurementField(measurement_class='Mass'),
        ),
    ]
