# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 20:14
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0017_auto_20170514_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlink',
            name='BuyPrice',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=10, verbose_name="Prix d'achat"),
        ),
    ]
