# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0018_auto_20170514_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productlink',
            old_name='BuyPrice',
            new_name='LinkBuyPrice',
        ),
        migrations.RenameField(
            model_name='productlink',
            old_name='BuyPrice_currency',
            new_name='LinkBuyPrice_currency',
        ),
    ]
