# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-14 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0019_auto_20170514_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlink',
            name='LinkBuyPrice',
        ),
        migrations.RemoveField(
            model_name='productlink',
            name='LinkBuyPrice_currency',
        ),
    ]
