# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 11:10
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('backoffice', '0022_product_mainphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
