# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 12:24
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0023_product_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReferences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ref', models.CharField(blank=True, max_length=200, null=True)),
                ('BuyPrice_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('HKD', 'Hong Kong Dollar'), ('GBP', 'Pound Sterling'), ('USD', 'US Dollar'), ('JPY', 'Yen'), ('CNY', 'Yuan Renminbi')], default='EUR', editable=False, max_length=3)),
                ('BuyPrice', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=10, null=True, verbose_name="Prix d'achat (€)")),
                ('SellPrice_currency', djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('HKD', 'Hong Kong Dollar'), ('GBP', 'Pound Sterling'), ('USD', 'US Dollar'), ('JPY', 'Yen'), ('CNY', 'Yuan Renminbi')], default='EUR', editable=False, max_length=3)),
                ('SellPrice', djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=10, null=True, verbose_name='Prix de vente (€)')),
            ],
            options={
                'verbose_name_plural': 'References',
                'verbose_name': 'Reference',
            },
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Images du produit', 'verbose_name_plural': 'Images du produit'},
        ),
        migrations.AlterModelOptions(
            name='productlink',
            options={'verbose_name': 'Liens vers les sites de vente', 'verbose_name_plural': 'Liens vers les sites de vente'},
        ),
        migrations.AlterField(
            model_name='product',
            name='BuyPrice',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='EUR', max_digits=10, null=True, verbose_name="Prix d'achat (€)"),
        ),
        migrations.AlterField(
            model_name='product',
            name='SellPrice',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='EUR', max_digits=10, null=True, verbose_name='Prix de vente (€)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='productreferences',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='MainProductReference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='backoffice.ProductReferences'),
        ),
    ]
