# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 12:52
from __future__ import unicode_literals

from django.db import migrations
import django_measurement.models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0024_auto_20170516_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreferences',
            name='Weight',
            field=django_measurement.models.MeasurementField(blank=True, measurement_class='Mass', null=True),
        ),
    ]
