# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 12:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0025_productreferences_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreferences',
            name='Weight',
        ),
    ]
