# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0026_remove_productreferences_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreferences',
            name='Measure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productreferences',
            name='MeasureUnit',
            field=models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('cl', 'cl'), ('l', 'l')], default='g', max_length=3),
        ),
    ]
