# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0027_auto_20170516_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreferences',
            name='Ref',
            field=models.CharField(max_length=200),
        ),
    ]
