# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 13:11
from __future__ import unicode_literals

from django.db import migrations
import django_measurement.models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0028_auto_20170516_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlink',
            name='LinkBuyPrice',
        ),
        migrations.RemoveField(
            model_name='productlink',
            name='LinkBuyPrice_currency',
        ),
        migrations.AlterField(
            model_name='product',
            name='BuyPrice',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='EUR', max_digits=10, null=True, verbose_name="Prix d'achat (remplacé par Référence produit, à inactiver)"),
        ),
        migrations.AlterField(
            model_name='product',
            name='SellPrice',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='EUR', max_digits=10, null=True, verbose_name='Prix de vente (remplacé par Référence produit, à inactiver)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Weight',
            field=django_measurement.models.MeasurementField(blank=True, measurement_class='Mass', null=True, verbose_name='Poids (remplacé par Référence produit, à inactiver)'),
        ),
    ]
