# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0029_auto_20170516_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='RefCount',
            field=models.SmallIntegerField(default=0),
        ),
    ]
