# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-16 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0030_product_refcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='RefCount',
            field=models.SmallIntegerField(default=0, verbose_name='Références'),
        ),
    ]
