# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-19 13:53
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0035_auto_20170518_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=filer.fields.image.FilerImageField(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='filer.Image'),
        ),
    ]
