# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-21 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0036_auto_20170519_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='MainPhoto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='backoffice.ProductImage'),
        ),
    ]
