# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-21 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0037_auto_20170521_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='Type_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Catégorie de produits'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='Type_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Catégorie de produits'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='Type_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='Catégorie de produits'),
        ),
    ]
