# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-21 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django_countries.fields
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0038_auto_20170521_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Description_fr',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='Description_zh_hans',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ProductName_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Nom du produit'),
        ),
        migrations.AddField(
            model_name='product',
            name='ProductName_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Nom du produit'),
        ),
        migrations.AddField(
            model_name='product',
            name='ProductName_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='Nom du produit'),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='Name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='Name_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='Name_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='Marque'),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='OriginCountry_en',
            field=django_countries.fields.CountryField(max_length=2, null=True, verbose_name="Pays d'origine"),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='OriginCountry_fr',
            field=django_countries.fields.CountryField(max_length=2, null=True, verbose_name="Pays d'origine"),
        ),
        migrations.AddField(
            model_name='productbrand',
            name='OriginCountry_zh_hans',
            field=django_countries.fields.CountryField(max_length=2, null=True, verbose_name="Pays d'origine"),
        ),
        migrations.AddField(
            model_name='productreferences',
            name='Ref_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productreferences',
            name='Ref_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productreferences',
            name='Ref_zh_hans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='productsubtype',
            name='SubType_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Sous-atégorie de produits'),
        ),
        migrations.AddField(
            model_name='productsubtype',
            name='SubType_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='Sous-atégorie de produits'),
        ),
        migrations.AddField(
            model_name='productsubtype',
            name='SubType_zh_hans',
            field=models.CharField(max_length=200, null=True, verbose_name='Sous-atégorie de produits'),
        ),
    ]
