# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-21 17:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0039_auto_20170521_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productbrand',
            name='OriginCountry_en',
        ),
        migrations.RemoveField(
            model_name='productbrand',
            name='OriginCountry_fr',
        ),
        migrations.RemoveField(
            model_name='productbrand',
            name='OriginCountry_zh_hans',
        ),
    ]
