# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 12:44
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0041_auto_20170521_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productbrand',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'managed': True, 'verbose_name': 'Images du produit', 'verbose_name_plural': 'Images du produit'},
        ),
        migrations.AlterModelOptions(
            name='productlink',
            options={'managed': True, 'verbose_name': 'Liens vers les sites de vente', 'verbose_name_plural': 'Liens vers les sites de vente'},
        ),
        migrations.AlterModelOptions(
            name='productreferences',
            options={'managed': True, 'verbose_name': 'Reference', 'verbose_name_plural': 'References'},
        ),
        migrations.AlterModelOptions(
            name='productsubtype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='producttype',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='productreferences',
            name='SellPrice_en',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=10, null=True, verbose_name='Prix de vente (€)'),
        ),
        migrations.AddField(
            model_name='productreferences',
            name='SellPrice_en_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('HKD', 'Hong Kong Dollar'), ('GBP', 'Pound Sterling'), ('USD', 'US Dollar'), ('JPY', 'Yen'), ('CNY', 'Yuan Renminbi')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='productreferences',
            name='SellPrice_fr',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=10, null=True, verbose_name='Prix de vente (€)'),
        ),
        migrations.AddField(
            model_name='productreferences',
            name='SellPrice_fr_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('HKD', 'Hong Kong Dollar'), ('GBP', 'Pound Sterling'), ('USD', 'US Dollar'), ('JPY', 'Yen'), ('CNY', 'Yuan Renminbi')], default='EUR', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='productreferences',
            name='SellPrice_zh_hans',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=Decimal('0'), default_currency='EUR', max_digits=10, null=True, verbose_name='Prix de vente (€)'),
        ),
        migrations.AddField(
            model_name='productreferences',
            name='SellPrice_zh_hans_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('HKD', 'Hong Kong Dollar'), ('GBP', 'Pound Sterling'), ('USD', 'US Dollar'), ('JPY', 'Yen'), ('CNY', 'Yuan Renminbi')], default='EUR', editable=False, max_length=3),
        ),
    ]
